name: main

on:
  push:
    branches: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: setup toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: cargo test
        run: cargo test --all-features

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --all --all-features --tests -- -D warnings

      - name: install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: run cargo-tarpaulin
        run: cargo tarpaulin --all-features --verbose